// File generated by FlutterFire CLI / custom configuration for shiftpay-7e0ff.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmuucT8MxzjPUJ8bt1k52VZ0-0Gm6criQ',
    appId: '1:92963925931:android:6f59a557cee9b7f3a52cee',
    messagingSenderId: '92963925931',
    projectId: 'shiftpay-7e0ff',
    storageBucket: 'shiftpay-7e0ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmuucT8MxzjPUJ8bt1k52VZ0-0Gm6criQ',
    appId: '1:92963925931:ios:6f59a557cee9b7f3a52cee',
    messagingSenderId: '92963925931',
    projectId: 'shiftpay-7e0ff',
    storageBucket: 'shiftpay-7e0ff.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmuucT8MxzjPUJ8bt1k52VZ0-0Gm6criQ',
    appId: '1:92963925931:web:6f59a557cee9b7f3a52cee',
    messagingSenderId: '92963925931',
    projectId: 'shiftpay-7e0ff',
    storageBucket: 'shiftpay-7e0ff.firebasestorage.app',
  );
}
